gate:
  ignore:
    startWith: /static,/admin/user/system,/admin/user/menu,/back/user/modifyPwd,/admin/marketInfo/newsHref
    contain: .
  oauth:
    prefix: /api

  jwt:
    secret: Xe*g@1jda
#2小时
    expiration: 7200
    header: access-token
  kdc:
    enabled: false
    ad-domain: NCAMC.local
    ad-server: ldap://vm-bgdc4.NCAMC.local/
#    ad-server: ldap://jf-officedc0.NCAMC.local/
    service-principal: HTTP/jf-iacluster-2@NCAMC.local
    keytab-location: C:/krb5.keytab
    ldap-search-base: dc=ncamc,dc=local
    ldap-search-filter: "(| (userPrincipalName={0}) (sAMAccountName={0}))"