ia:
  datasource:
#    url: jdbc:oracle:thin:@172.16.1.205:1521:orcl
    url: jdbc:oracle:thin:@10.10.3.34:1521:orcl
    username: ia
    password: ia2_pwd0927
#    password: ia1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
ch:
  driver-class-name: net.sourceforge.jtds.jdbc.Driver
  url: jdbc:jtds:sqlserver://10.3.3.30:1433/fcdb
  username: chdb
  password: ncamc
hy:
  datasource:
    url: jdbc:oracle:thin:@10.10.3.34:1521:orcl
    username: ia
    password: ia2_pwd0927
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20